config/routes.rb
Rails.application.routes.draw do

  get 'tried_vendors/create'

  resources :vendors do
    resources :comments, only: [:show, :create, :destroy]
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  resources :users, only: [:show, :index, :update]

  resources :tried_vendors
  resources :products, :path => "brands" do
    resources :comments, only: [:show, :create, :destroy]
     resources :follows, only: [:create, :destroy]
  end

  root 'products#index'

end

app/models/vendor.rb
require 'crunchbase'

class Vendor < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "200x200>"}
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  has_many :customers
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :products, :through => :customers


#add button 
#rails runner scrapeall.rb in console
  def scrape_crunchbase
    crunchdoc = Crunchbase.new( crunchbase_url(:organization) ) rescue nil
    #crunchdoc ||= Crunchbase.new( crunchbase_url(:product) ) rescue nil

    if crunchdoc
      self.description = crunchdoc.scrape_description
      self.website = crunchdoc.scrape_website
    else
      logger.info "Could not open and scrape Crunchbase for #{vendor_name}"
    end
  end

  def self.search(query)
    if Rails.env.production?
      where("vendor_name ilike ?", "%#{query}%") #todo: autopop and return non exact searches
    else
      where("vendor_name like ?", "%#{query}%") #todo: autopop and return non exact searches
    end
  end 

  def crunchbase_url(what)
    whatname = vendor_name.downcase
    "https://www.crunchbase.com/#{what}/#{whatname}"
  end
  
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
    @vendor = Vendor.new
    @comment = @vendor.comments

    if params[:search]
      @vendors = Vendor.search(params[:search])
    else
      @vendors = Vendor.all
    end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])
    @comments = @vendor.comments
    @comment = Comment.new
    @product = Product.new
    @tried_vendor = TriedVendor.new
    #getting error 'undefined method `to_sym' for nil:NilClass'
    @products = @vendor.products
    @vendor = Vendor.includes(:products).find(params[:id])
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:image, :vendor_name, :about,  { :product_ids =>[] })
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for @vendor, html: { multipart: true } do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this tech from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :vendor_name %><br>
    <%= f.text_field :vendor_name %>
  </div>
    <div class="form-group">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>

  <div class = "form-group">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class = "form-group">
     <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <% Product.all.each do |product| %>
    <div>
    <%= hidden_field_tag "vendor[product_ids][]", nil%>
    <%= check_box_tag "vendor[product_ids][]", product.id, @vendor.product_ids.include?(product.id), id: dom_id(product) %>
    <%= label_tag dom_id(product), product.name %> <br/>
    </div>
    <% end %>
    <%= submit_tag %>
    <% end %>

app/views/vendors/_product.html.erb
<% if is_user? %>
  <% Product.all.each do |product| %>
    <% if @vendor.product_ids.include?(product.id) %>
    <%= link_to image_tag(product.image.url(:thumb)), product %>
    <% end %>
  <% end %>
<% else %>
<p> <%= link_to "Sign in With Linkedin", user_omniauth_authorize_path(:linkedin) %> to see the comprehensive list</p>
  <% Product.take(2).each do |product| %>
    <% if @vendor.product_ids.include?(product.id) %>
      <%= link_to image_tag(product.image.url(:thumb)), product %>
    <% end %>
  <% end %> 
<% end %>

app/views/vendors/edit.html.erb
<% if is_admin? %>
<div class = "container">
  <h1>Editing vendor</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @vendor %> |
  <%= link_to 'Back', vendors_path %>
</div>
<% end %>

app/views/vendors/index.html.erb
<div class="content">
  <div id="products" class="transitions-enabled">
    <% @vendors.each do |vendor| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(vendor.image.url(:medium)), vendor %>
        <div class="panel-body">
          <p><%= vendor.vendor_name %> | <%= vendor.comments.count %> comments </p>
          <% if is_admin? %>
            <%= link_to 'Edit', edit_vendor_path(vendor) %>
            <!-- todo: add authorization for delete button -->
            <%= link_to 'Delete', vendor, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/vendors/new.html.erb
<% if is_admin? %>
    <div class = "container">
      <h1>New vendor</h1>

      <%= render 'form' %>

      <%= link_to 'Back', vendors_path %>
    </div>
  <% end %>

app/views/vendors/show.html.erb
<div class="show-container"
  <div class="row">
    <div class="col-md-4">
<div id= "vendor-head">

  <h4> Vendor </h4>
</div>
 

        <%= image_tag @vendor.image.url(:medium) %>
        <p><%= @vendor.vendor_name %> </p>
        <p><%= @vendor.about %> </p>
        <p> <%= link_to @vendor.website, @vendor.website %> </p>
        <p> <%= @vendor.description %> </p>
        <% if is_admin? %>
          <%= link_to 'Edit', edit_vendor_path %> |
          <%= link_to 'Back', vendors_path %> |
          <%= link_to 'Delete', @vendor, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      </p>
    </div>

<div class="col-md-4">
  <div id= "vendor-head">
    <h4> Brands they work with </h4>

    <%= render 'product' %>
      </div>
</div> 

  <div class="col-md-4">
    <div id="vendor-head">
     <% if user_signed_in? %>
        <%= render partial: 'tried_vendors/tried_vendors' %>
      <%- end -%>
       <%= render partial: 'comments/vcomments' %>
      </div> 
    </div>
  </div>
</div>