config/routes.rb
Rails.application.routes.draw do

  get 'tried_vendors/create'

  resources :vendors do
    resources :comments, only: [:show, :create, :destroy]
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  resources :users, only: [:show, :index, :update]

  resources :tried_vendors
  resources :products, :path => "brands" do
    resources :comments, only: [:show, :create, :destroy]
     resources :follows, only: [:create, :destroy]
  end

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "200x200>" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :customers
  has_many :vendors, :through => :customers
  has_many :follows, dependent: :destroy

#search test
  def self.search(query)
    where("name like?", "%#{query}%") #todo: autopop and return non exact searches
  end 

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

#admin controller action jon test
  #before_action :admin_required, only: [:edit, :create]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @product = Product.new
    @comments = @product.comments
    if params[:search]
      @products = Product.search(params[:search])
      if @products.empty?
        return redirect_to vendors_path(search: params[:search])
      end
    else
      @products = Product.all
    end
  end

 
  # GET /products/1
  # GET /products/1.json
  def show
    # @product = Product.find(params[:id])
    @product = Product.includes(:vendors).find(params[:id])
    @comment = Comment.new
    @comments = @product.comments
    # @comment = Comment.new
    # @vendor = Vendor.new
    @vendors = @product.vendors
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, bunnotice: 'Your brand has been added' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params) #added _attributes
        format.html { redirect_to @product, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Brand was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, { :vendor_ids =>[] })
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
  <%= form_for @product, html: { multipart: true } do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this brand from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :image %><br>
      <%= f.file_field :image, class: "form-control" %>
    </div>
  <!-- test -->
      <p> TODO: Make Alphabetical order </p>
  <% Vendor.order(:vendor_name).all.each do |vendor| %>
    <div>
    <%= hidden_field_tag "product[vendor_ids][]", nil%>
    <%= check_box_tag "product[vendor_ids][]", vendor.id, @product.vendor_ids.include?(vendor.id), id: dom_id(vendor) %>
    <%= label_tag dom_id(vendor), vendor.vendor_name %> <br/>

    </div>
    <% end %>
    <%= submit_tag %>
    <% end %>

app/views/products/_index.html.erb
<% @products.each do |product| %>
<div class="img-thumbnail"><%= image_tag product.image.url(:thumb), alt: product.image.url(:thumb) %></div>
<% end %>

app/views/products/_vendor.html.erb
<% if is_user? %>
  <% Vendor.all.each do |vendor| %>
    <% if @product.vendor_ids.include?(vendor.id) %>
    <%= link_to image_tag(vendor.image.url(:thumb)), vendor %>
    <% end %>
  <% end %>
<% else %>
  <p><%= link_to "Sign in With Linkedin", user_omniauth_authorize_path(:linkedin) %> to see the comprehensive list</p>
    <% Vendor.take(2).each do |vendor| %>
      <% if @product.vendor_ids.include?(vendor.id) %>
        <%= link_to image_tag(vendor.image.url(:thumb)), vendor %> 
      <% end %>
    <% end %>
<% end %>

app/views/products/edit.html.erb
<% if is_admin? %>
<div class = "container">
  <h1>Edit Brand</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>

</div>

<% else %>

<% end %>

app/views/products/index.html.erb
<% unless is_user? %>
<div class = "jumbotron">
  <div class = "row">
    <div class= "col-md-4"> 
    </div>

      <div class = "home-btns">
        <div id= "home-fun"> 
          <h2>Explore Digital Technologies Brands Use</h2>
           <p><%= link_to "Sign in With Linkedin", user_omniauth_authorize_path(:linkedin), class: "btn btn-info btn-lg" %></p>
           <small> <button type="button" data-toggle="popover" title="Popover title" data-content="Because we want to keep it professional">Why Linkedin? </button>
         </small>


        </div>
    </div>
  </div>
</div>

<div class="content">
  
  <div id="products" class="transitions-enabled">
    <% @products.each do |product| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(product.image.url(:medium)) %>
        <div class="panel-body">
          
          <% if is_admin? %>
            <%= link_to 'Edit', edit_product_path(product) %>
            <!-- todo: add authorization for delete button -->
            <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
            
        </div>
      </div>
    <% end %>
  </div>
</div>


<% else %> 

<div>
  <%= session[:positions] %>
</div>
<div class="content">
  <div id="products" class="transitions-enabled">
    <% @products.each do |product| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(product.image.url(:medium)), product %>
        <div class="panel-body">
          
          <% if is_admin? %>
            <%= link_to 'Edit', edit_product_path(product) %>
            <!-- todo: add authorization for delete button -->
            <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
            
        </div>
      </div>
    <% end %>
  </div>
</div>


<% end %>

app/views/products/index.js.erb
$(".index").html("<%= escape_javascript(render('index')) %>")

app/views/products/new.html.erb
<% if is_admin? %>
  <div class = "container">
    <h1>Add a Brand</h1>

    <%= render 'form' %>

    <%= link_to 'Back', products_path %>
  </div> 
<% end %>

app/views/products/show.html.erb
<div class="show-container"
  <div class="row">
    <div class="col-md-4">
      <div id="brand-head"> 
        <% if is_user? %>
          <%= render partial: 'follows/follow', locals: { product: @product } %>
        <% end %>
        <h4> Company </h4>
     </div>

        <%= image_tag @product.image.url(:medium) %>
        <p><%= @product.name %> </p>

        <% if is_admin? %>
          <%= link_to 'Edit', edit_product_path(@product) %>|
          <%= link_to 'Back', products_path %> |
          <%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </p>
      </div>

    <div class="col-md-4">
      <div id= "brand-head">
        <h4> Tech </h4>
          <%= render 'vendor' %>
      </div>
    </div> 

    <div class= "col-md-4">
      <%= render partial: 'comments/pcomment' %>
    </div>
  </div>