config/routes.rb
Rails.application.routes.draw do

  get 'tried_vendors/create'

  resources :vendors do
    resources :comments, only: [:show, :create, :destroy]
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  resources :users, only: [:show, :index, :update]

  resources :tried_vendors
  resources :products, :path => "brands" do
    resources :comments, only: [:show, :create, :destroy]
     resources :follows, only: [:create, :destroy]
  end

  root 'products#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechTrack.co </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<!-- ****** NAVBAR START ***** -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TechTrack.co', root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
    <% if is_admin? %>
          <li><%= link_to 'Add Vendor', new_vendor_path %></li>
          <li><%= link_to 'Add Brand', new_product_path %></li>
    <% end %>
        
      </ul>
<%= form_tag products_path, :method => "get", id: "search-form", class: "navbar-form navbar-left", role: "search" do %>
        <div class="form-group">

          <!-- search test / todo: make search work on all pages and also search for vendors-->

    <%= text_field_tag :search, params[:search], placeholder: "Search by technology or brand", :class => "form-control" %>
    <%= submit_tag "Search", :name => nil, :class => "btn btn-default" %>
  <% end %>

        </div>
       
      </form>
    <ul class="nav navbar-nav navbar-right">  
    <li>  <% if current_user %>
      
    <%= link_to (current_user.name || current_user.email), current_user %> <% end %></li>  
      <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">  <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Brands', products_path %></li>
            <li><%= link_to 'Vendors', vendors_path %></li>
            <li class="divider"></li>
            <li>
              <% if current_user %>
                <%= link_to 'Settings', edit_user_registration_path %>
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
                <% else %> 
                <li> <%= link_to "Sign In", new_user_session_path %> </li>
                <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- NAVBAR END -->

<!-- ****** ALERTS ******* -->

       <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:error] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>



    <%= yield %>





  </body>
</html>